#name: Build systemdashboard
#on:
#  push:
#    branches: [main]
#jobs:
#  build:
#    runs-on: docker
#    steps:
#      - uses: actions/checkout@v3
#      - name: Build & Push
#        run: |
#          docker build -t 192.168.1.138:3000/david/systemdashboard:latest .
#          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_TOKEN }} 192.168.1.138:3000
#          docker push 192.168.1.138:3000/david/systemdashboard:latest
name: Test
on: [push]
jobs:
  test:
    runs-on: docker
    container: docker:latest
    steps:
      - name: Test Docker
        run: docker --version
      - name: Hello World
        run: echo "Hello from Forgejo Runner"
