name: Build & Push
on: [push]
jobs:
  build:
    runs-on: docker
    container: docker:latest
    env:
      DOCKER_HOST: tcp://docker-in-docker:2375
    steps:
      - run: apk add --no-cache git
      - run: git clone https://git.keurigsweb.com/david/systemdashboard.git . && git checkout ${{ github.sha }}
      - run: docker build -t forgejo:3000/david/systemdashboard:latest .
      - run: docker login -u david -p ${{ secrets.REGISTRY_TOKEN }} forgejo:3000
      - run: docker push forgejo:3000/david/systemdashboard:latest
